name: submit-CRAN

on:
  push:
    branches: [main, master]
    tags: [ '*.*' ]
  pull_request:
    branches: [main, master]

env:
  DEBUG_CI: true

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'release'

    - uses: r-lib/actions/setup-r-dependencies@v2

    - run: |
        cd ..; R CMD build smint 
        mkdir smint/CRAN-${{ matrix.os }}
        mv smint_*.* smint/CRAN-${{ matrix.os }}/.
      shell: bash
      name: R CMD build
    - run: |
        R CMD check --as-cran --no-manual CRAN-${{ matrix.os }}/smint* || (
          test -f smint.Rcheck/00install.out && cat smint.Rcheck/00install.out | sed -e 's/^/00install.out| /';
          exit 1
        )
      shell: bash
      name: R CMD check
    - uses: actions/upload-artifact@v2
      with:
        path: ./CRAN-*

    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./CRAN-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}